services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: bankUser
      POSTGRES_PASSWORD: bankPassword
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
